### ISSUE TITLE
 I get this error  after  running npm start

### ISSUE THREAD

**Issue by Osezno** [meatspaces/meatspace-chat-v2#103]
/home/jose/meatspace-chat-v2/node_modules/meatspace-publico/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/jose/meatspace-chat-v2/node_modules/meatspace-publico/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/jose/meatspace-chat-v2/node_modules/meatspace-publico/node_modules/level/node_modules/leveldown/index.js:1:99)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/home/jose/.nvm/versions/node/v4.0.0/bin/node" "/home/jose/.nvm/versions/node/v4.0.0/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! meatspace-chat@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meatspace-chat@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meatspace-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meatspace-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meatspace-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jose/meatspace-chat-v2/npm-debug.log

**Comment by MylesBorins** [comment]
can you try updating to node v4.4.1. Node v4.0.0 is not actively supported and known to be buggy

**Comment by Osezno** [comment]
I updated the node version  to v4.4.1   but still  get this error  any ideas what  i migth be doing wrong

jose@jose-Aspire-V5-551:~/meatspace-chat-v2$ npm start

> meatspace-chat@1.0.0 start /home/jose/meatspace-chat-v2
> node index.js

/home/jose/meatspace-chat-v2/node_modules/hapi/node_modules/hoek/lib/index.js:638
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Bad server constructor arguments: duplicated arg type: string (values: `localhost`, `port`)
    at Object.exports.assert (/home/jose/meatspace-chat-v2/node_modules/hapi/node_modules/hoek/lib/index.js:638:11)
    at Function.internals.Pack._args (/home/jose/meatspace-chat-v2/node_modules/hapi/lib/pack.js:159:14)
    at Object.exports.createServer (/home/jose/meatspace-chat-v2/node_modules/hapi/lib/index.js:28:21)
    at Object.<anonymous> (/home/jose/meatspace-chat-v2/index.js:14:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/home/jose/.nvm/versions/node/v4.4.1/bin/node" "/home/jose/.nvm/versions/node/v4.4.1/bin/npm" "start"
npm ERR! node v4.4.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! meatspace-chat@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meatspace-chat@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meatspace-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meatspace-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meatspace-chat
npm ERR! There is likely additional logging output above.
